version: '3.1'
services:
  dbpostgresql:
    container_name: postgres
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=products
  app:
    container_name: product-manager
    image: product-manager
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - dbpostgresql

volumes:
  postgres-data: